let shirts_data = [
    {
        id:100,
        name:"Men Slim Fit Solid..",
        full_name:"Men Slim Fit Solid Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/b/w/o/s-c301-white-dennis-lingo-original-imafw2ggrk5epcfu-bb.jpeg?q=70",
        new_price:499,
        old_price:1849,
        discount:"73% off",
        rating:4.1
    },
    {
        id:101,
        name:"Men Slim Fit Solid..",
        full_name:"Men Slim Fit Solid Cut Away Collar Casual Shirt",
        brand_name:"LOCOMOTIVE",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/s/c/9/l-lmos000183-locomotive-original-imahfg3gazyhpzaw.jpeg?q=70",
        new_price:1166,
        old_price:3499,
        discount:"66% off",
        rating:undefined
    },
    {
        id:102,
        name:"Men Slim Fit Chec..",
        full_name:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/y/8/g/xl-c751-d-blue-dennis-lingo-original-imafnyksvpjybggz-bb.jpeg?q=70",
        new_price:549,
        old_price:2499,
        discount:"78% off",
        rating:4.1
    },
    {
        id:103,
        name:"Men Slim Fit Chec..",
        full_name:"Men Slim Fit Checkered Cut Away Collar Casual Shirt",
        brand_name:"HIGHLANDER",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/w/n/x/m-phsh000014-highlander-original-imagz7uftyy9tfnt.jpeg?q=70",
        new_price:511,
        old_price:1799,
        discount:"71% off",
        rating:4.1
    },
    {
        id:104,
        name:"Men Regular Fit..",
        full_name:"Men Regular Fit Self Design Spread Collar Casual Shirt",
        brand_name:"CAMPUS SUTRA",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/h/k/q/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrswwhtbc4d.jpeg?q=70",
        new_price:854,
        old_price:1899,
        discount:"55% off",
        rating:4
    },
    {
        id:105,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Casual Shirt",
        brand_name:"Roadster",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/d/k/v/40-2284526-roadster-original-imafgmtuhfx3nprm-bb.jpeg?q=70",
        new_price:533,
        old_price:1299,
        discount:"58% off",
        rating:4.1
    },
    {
        id:106,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Cut Away Collar Casual Shirt",
        brand_name:"KETCH",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/kvlaaa80/shirt/g/t/n/l-khsh000333-ketch-original-imag8gmyy4mgcajh.jpeg?q=70",
        new_price:482,
        old_price:899,
        discount:"46% off",
        rating:3.8
    },
    {
        id:107,
        name:"Men Slim Fit Check..",
        full_name:"Men Slim Fit Checkered Spread Collar Casual Shirt",
        brand_name:"The Indian Garage Co. ",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/s/b/w/-original-imagz8h9b6uhqarq.jpeg?q=70",
        new_price:489,
        old_price:1749,
        discount:"72% off",
        rating:4.1
    },
    {
        id:108,
        name:"Men Regular Fit Ch..",
        full_name:"Men Regular Fit Checkered Casual Shirt",
        brand_name:"The Indian Garage Co. ",
        category:"men-shirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/k/p/s/xl-0921-ovrsh113-06-the-indian-garage-co-original-imagg22gz3x4d5nu.jpeg?q=70",
        new_price:721,
        old_price:1849,
        discount:"61% off",
        rating:4.2
    },
    {
        id:109,
        name:"Men Printed Round..",
        full_name:"Men Printed Round Neck Polyester White, Black T-Shirt",
        brand_name:"sti",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/o/t/m-gucci-tshirt-sti-original-imahf7w3dkxzkd6g.jpeg?q=70",
        new_price:199,
        old_price:999,
        discount:"80% off",
        rating:3.9
    },
    {
        id:110,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Cotton Blend Blue T-Shirt",
        brand_name:"Leotude",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/k/b/s-fs49-blue-gorilla-c1-leotude-original-imahfzwzyfp25ec2.jpeg?q=70",
        new_price:329,
        old_price:1099,
        discount:"70% off",
        rating:4
    },
    {
        id:111,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Cotton Blend Pink T-Shirt",
        brand_name:"Jack Paris",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/m/v/s-courage-the-cowardly-dog-men-1-pink-s-jack-paris-original-imahfv79cqyhz4bt.jpeg?q=70",
        new_price:440,
        old_price:1499,
        discount:"70% off",
        rating:undefined
    },
    {
        id:112,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton Black T-Shirt",
        brand_name:"Mavinclub",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/h/g/h/l-neverlookback-10-mavinclub-original-imah22sjktyjhkrj.jpeg?q=70",
        new_price:275,
        old_price:999,
        discount:"72% off",
        rating:3.9
    },
    {
        id:113,
        name:"Men Striped Round N..",
        full_name:"Men Striped Round Neck Cotton Blend Light Green T-Shirt",
        brand_name:"FIONAA TRENDZ ",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/w/y/l-oversized-fionaa-trendz-original-imagmngnpnha7c9n.jpeg?q=70",
        new_price:255,
        old_price:999,
        discount:"74% off",
        rating:3.9
    },
    {
        id:114,
        name:"Oversized Men Printed..",
        full_name:"Oversized Men Printed, Typography Round Neck Pure Cotton Navy Blue T-Shirt",
        brand_name:"Veirdo",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/p/v/l-os-100-vdorgnl-nvy-veirdo-original-imah256cvtzjwn5r.jpeg?q=70",
        new_price:359,
        old_price:1199,
        discount:"70% off",
        rating:4.1
    },
    {
        id:115,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton White T-Shirt",
        brand_name:"BUKKL",
        category:"men-tshirts",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-t-shirt/x/b/o/xl-t-29-1st-bukkl-original-imagnwdswu5jv4gj.jpeg?q=70",
        new_price:299,
        old_price:1999,
        discount:"85% off",
        rating:4
    },
    {
        id:116,
        name:"Men Tapered Fit Mid..",
        full_name:"Men Tapered Fit Mid Rise Light Blue Jeans",
        brand_name:"HIGHLANDER",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/x/u/i/36-hljn001993-highlander-original-imagajtfg8an4f9j-bb.jpeg?q=70",
        new_price:723,
        old_price:1799,
        discount:"59% off",
        rating:3.8
    },
    {
        id:117,
        name:"Men Regular Mid Rise..",
        full_name:"Men Regular Mid Rise Light Blue Jeans",
        brand_name:"DENIM FIT",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/9/6/t/28-pf-mj-lb-baggy03-denim-fit-original-imahyhqa2hz9mrez.jpeg?q=70",
        new_price:499,
        old_price:2499,
        discount:"80% off",
        rating:3.2
    },
    {
        id:118,
        name:"Men Relaxed Fit Mid..",
        full_name:"Men Relaxed Fit Mid Rise Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/0/a/34-united192-united-denim-original-imagyvu67vpm68dh.jpeg?q=70",
        new_price:654,
        old_price:2999,
        discount:"78% off",
        rating:3.9
    },
    {
        id:119,
        name:"Men Slim Mid Rise..",
        full_name:"Men Slim Mid Rise Blue Jeans",
        brand_name:"KILLER",
        category:"men-jeans",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/o/r/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhkajy6fdh.jpeg?q=70",
        new_price:1539,
        old_price:3899,
        discount:"60% off",
        rating:3.8
    },
    {
        id:120,
        name:"Men Jogger Fit Mid..",
        full_name:"Men Jogger Fit Mid Rise Black Jeans",
        brand_name:"Nayak Fashion",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/z/s/c/30-o-black-tissu-amour-original-imagrvgzuwcx8sc6.jpeg?q=70",
        new_price:497,
        old_price:1999,
        discount:"75% off",
        rating:3.8
    },
    {
        id:121,
        name:"Men Slim Low Rise..",
        full_name:"Men Slim Low Rise Dark Blue Jeans",
        brand_name:"Louis Philippe Jeans ",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/b/g/j/32-lrdncslpo78544-louis-philippe-jeans-original-imagu2mszzbqqysh.jpeg?q=70",
        new_price:1767,
        old_price:2599,
        discount:"32% off",
        rating:4
    },
    {
        id:122,
        name:"Men Relaxed Fit M..",
        full_name:"Men Relaxed Fit Mid Rise Light Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men-jeans",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/t/v/j/28-united069-united-denim-original-imahyur5964ehvjn.jpeg?q=70",
        new_price:649,
        old_price:2999,
        discount:"78% off",
        rating:3.9
    },
    {
        id:123,
        name:"Synthetic Leather Lightw..",
        full_name:"Synthetic Leather |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor|Daily Use Sneakers For Men (White)",
        brand_name:"aadi",
        category:"men-shoes",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/v/9/6-tm-12-6-trm-white-original-imagjqyzntcvcmhz.jpeg?q=70",
        new_price:285,
        old_price:1999,
        discount:"85% off",
        rating:3.6
    },
    {
        id:124,
        name:"Casual Sneaker Shoes..",
        full_name:"Casual Sneaker Shoes for Men | Classic Rounded Toe, Soothing Insole Sneakers For Men  (Blue, Off White)",
        brand_name:"Red Tape",
        category:"men-shoes",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/n/o/f/-original-imahfxv9rwh5nvhp.jpeg?q=70",
        new_price:1649,
        old_price:5499,
        discount:"70% off",
        rating:4.3
    },
    {
        id:125,
        name:"Boots For Men(Bla..",
        full_name:"Boots For Men  (Black)",
        brand_name:"Vellinto",
        category:"men-shoes",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/e/j/e/6-art-ca474-vellinto-black-original-imahy5mxqzxrhezg.jpeg?q=70",
        new_price:696,
        old_price:1999,
        discount:"65% off",
        rating:4.4
    },
    {
        id:126,
        name:"Puma Smashic Sneak..",
        full_name:"Puma Smashic Sneakers For Men  (White)",
        brand_name:"PUMA",
        category:"men-shoes",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/q/g/l/-original-imagsfdvebvyzkxa.jpeg?q=70",
        new_price:1999,
        old_price:4499,
        discount:"55% off",
        rating:4.1
    },
    {
        id:127,
        name:"Loafers For Men (Bro..",
        full_name:"Loafers For Men  (Brown)",
        brand_name:"Bata",
        category:"men-shoes",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/m/y/a/-original-imaghhz3mzfrghf3.jpeg?q=70",
        new_price:692,
        old_price:999,
        discount:"30% off",
        rating:4.1
    },
    {
        id:128,
        name:"Men Solid Cotton Ble..",
        full_name:"Men Solid Cotton Blend Straight Kurta  (White)",
        brand_name:"SOPANI",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/j/z/u/m-chainlster-sopani-original-imagtjhdf7azz8n2.jpeg?q=70",
        new_price:369,
        old_price:1499,
        discount:"75% off",
        rating:4
    },
    {
        id:129,
        name:"Men Printed Cotton B..",
        full_name:"Men Printed Cotton Blend Straight Kurta  (Yellow)",
        brand_name:"FRELURO ",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/l08gsy80/kurta/k/y/v/l-grey-106-yellow-freluro-original-imagc26vxzctqygv.jpeg?q=70",
        new_price:299,
        old_price:999,
        discount:"70% off",
        rating:3.9
    },
    {
        id:130,
        name:"Men Embroidered Co..",
        full_name:"Men Embroidered Cotton Silk Straight Kurta  (Black)",
        brand_name:"Nellist",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/4/c/p/m-only-kurta-box-nellist-original-imagvmkmtedryv9t.jpeg?q=70",
        new_price:499,
        old_price:1999,
        discount:"75% off",
        rating:3.7
    },
    {
        id:131,
        name:"Men Solid Cotton Bl..",
        full_name:"Men Solid Cotton Blend Straight Kurta  (White)",
        brand_name:"DEELMO",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/m/q/s/xxl-derfv04-deelmo-original-imagwzzzujt2r3wj.jpeg?q=70",
        new_price:494,
        old_price:1999,
        discount:"75% off",
        rating:4
    },
    {
        id:132,
        name:"Men Cotton Blend K..",
        full_name:"Men Cotton Blend Kurta Pyjama Set",
        brand_name:"VINAARI",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/c/u/j/l-plain-kurta-triveni-creation-original-imahybf9g54yvpch.jpeg?q=70",
        new_price:347,
        old_price:999,
        discount:"65% off",
        rating:3.8
    },
    {
        id:133,
        name:"Men Cotton Blend K..",
        full_name:"Men Cotton Blend Kurta Pyjama Set",
        brand_name:"FABWAX",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/t/z/h/xl-an-lp-k-only-anrex-original-imagyhkur4ynpg3p.jpeg?q=70",
        new_price:497,
        old_price:1699,
        discount:"70% off",
        rating:3.9
    },
    {
        id:134,
        name:"N.B.F Fashion Print..",
        full_name:"N.B.F Fashion Printed Sherwani",
        brand_name:"",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/sherwani/c/o/m/l-rj-985-n-b-f-fashion-original-imagweh47h9hdmkz.jpeg?q=70",
        new_price:1694,
        old_price:3999,
        discount:"57% off",
        rating:3.7
    },
    {
        id:135,
        name:"Men Pyjama",
        full_name:"Men Pyjama",
        brand_name:"Fashtastic",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/pyjama/f/y/b/l-pyjam1-fashtastic-original-imag9hfmdjjdrxjb-bb.jpeg?q=70",
        new_price:499,
        old_price:899,
        discount:"44% off",
        rating:4.1
    },
    {
        id:136,
        name:"EID Festive Wear..",
        full_name:"EID Festive Wear For Men Pyjama",
        brand_name:"VASTRAMAY",
        category:"men-ethnics",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/pyjama/k/y/4/free-vasmpty1wh-vastramay-original-imagfanh5cgzhe6y-bb.jpeg?q=70",
        new_price:395,
        old_price:1999,
        discount:"80% off",
        rating:3.7
    },
    {
        id:137,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Festive & Wedding Blazer (Black)",
        brand_name:"FUBAR",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/x/3/6/l-kcbz-blazer-bk-fubar-original-imahfh5qtt62vaac.jpeg?q=70",
        new_price:1499,
        old_price:4999,
        discount:"70% off",
        rating:3.6
    },
    {
        id:138,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Casual,Formal,Festive & Wedding,Party Blazer (Black)",
        brand_name:"Darbar In",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/7/n/i/xl-unique-black-darbar-in-original-imahfyh4t8pxzh94.jpeg?q=70",
        new_price:1529,
        old_price:5999,
        discount:"74% off",
        rating:3.7
    },
    {
        id:139,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Casual, Formal,Party,Festive & Wedding Blazer(Green)",
        brand_name:"HUMJOLI MENS WEAR ",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/u/z/y/xxl-xe-n4-grn-humjoli-mens-wear-original-imagywmu2pczhfr3.jpeg?q=70",
        new_price:1509,
        old_price:7999,
        discount:"81% off",
        rating:3.5
    },
    {
        id:140,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Casual Blazer  (Black)",
        brand_name:"Khalak",
        category:"men-blazers",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/v/o/u/s-105-man-blazer-black-swara-craft-original-imagsv24xkawafw6.jpeg?q=70",
        new_price:1199,
        old_price:1999,
        discount:"40% off",
        rating:3.6
    },
    {
        id:141,
        name:"Trending Premium Quality.",
        full_name:"Trending Premium Quality Day & Date Functioning for Boys Analog Watch - For Men SK-PG-4078-WYT-BRWN Basic with Day and Date Display",
        brand_name:"PROVOGUE ",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/e/v/e/1-sk-pg-4078-wyt-brwn-basic-with-day-and-date-display-provogue-original-imahffrywrx3x8zb.jpeg?q=70",
        new_price:299,
        old_price:2499,
        discount:"88% off",
        rating:3.9
    },
    {
        id:142,
        name:"Analog Watch-For..",
        full_name:"Analog Watch - For Men PE000017B",
        brand_name:"PETER ENGLAND",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/v/f/2/-original-imagrdzghye4wtqq.jpeg?q=70",
        new_price:1467,
        old_price:3045,
        discount:"51% off",
        rating:4.3
    },
    {
        id:143,
        name:"Provogue Functioning S..",
        full_name:"Provogue Functioning Stainless Chain Analog Watch - For Men SK-PG-4076-BLUWYT-SLVR Basic Analog Watch for Men with Day and Date Display",
        brand_name:"PROVOGUE",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/p/a/y/-original-imagrtbrqzwf8fjn.jpeg?q=70",
        new_price:359,
        old_price:2499,
        discount:"85% off",
        rating:3.6
    },
    {
        id:144,
        name:"Tees Analog Watch..",
        full_name:"Tees Analog Watch - For Men 68011PP08",
        brand_name:"Fastrack",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/a/k/e/-original-imagnydrewxe5qeg.jpeg?q=70",
        new_price:939,
        old_price:945,
        discount:undefined,
        rating:4.3
    },
    {
        id:145,
        name:"Flynn Analog Watch..",
        full_name:"Flynn Analog Watch-For Men BQ1125",
        brand_name:"FOSSIL",
        category:"men-watches",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/0/k/a/-original-imagphkyrrrnaryb.jpeg?q=70",
        new_price:5879,
        old_price:11995,
        discount:"50%off",
        rating:4.3
    },
    {
        id:146,
        name:"Apple AirPods(2nd gen)",
        full_name:"Apple AirPods(2nd gen) with Charging Case Bluetooth Headset with Mic  (White, True Wireless)",
        brand_name:"APPLE",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/612/612/kpinwy80/headphone/x/r/e/mmef2hn-a-apple-original-imag3qe9hphsevrt.jpeg?q=70",
        new_price:8499,
        old_price:12900,
        discount:"34%off",
        rating:4.5
    },
    {
        id:147,
        name:"realme Techlife Buds",
        full_name:"realme Techlife Buds T100 with up to 28 Hours Playback & AI ENC for Calls Bluetooth Headset  (Blue, True Wireless)",
        brand_name:"REALME",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/2/k/-original-imaghe5mtuu35bhk.jpeg?q=70",
        new_price:1399,
        old_price:2999,
        discount:"53%off",
        rating:4.2
    },
    {
        id:148,
        name:"boAt Airdopes 161",
        full_name:"boAt Airdopes 161/163 with ASAP Charge & 40 HRS Playback Bluetooth Headset  (Pebble Black, Active Black, True Wireless)",
        brand_name:"boAt",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/o/d/r/-original-imagpgwsm6zgtsrj.jpeg?q=70",
        new_price:999,
        old_price:2490,
        discount:"59%off",
        rating:4
    },
    {
        id:149,
        name:"OPPO Enco Buds 2",
        full_name:"OPPO Enco Buds 2 with 28 hours Battery life & Deep Noise Cancellation Bluetooth Headset  (Midnight, True Wireless)",
        brand_name:"OPPO",
        category:"men-earbuds",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/r/z/enco-buds-2-oppo-original-imagh9frfp7gxdb3.jpeg?q=70",
        new_price:1799,
        old_price:3999,
        discount:"55%off",
        rating:4.3
    },
    {
        id:150,
        name:"Men Regular Fit Sol..",
        full_name:"Men Regular Fit Solid Spread Collar Formal Shirt",
        brand_name:"Voroxy",
        category:"men-formals",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/i/j/c/2xl-csrmnkt-white-voroxy-original-imahfmcgg7vggdwm.jpeg?q=70",
        new_price:299,
        old_price:2199,
        discount:"86%off",
        rating:3.9
    },
    {
        id:151,
        name:"Men Regular Fit Sol..",
        full_name:"Men Regular Fit Solid Spread Collar Formal Shirt",
        brand_name:"VTEXX",
        category:"men-formals",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/d/w/b/s-13-lstr-peach-vtexx-original-imagxtnyc2c4fgdu.jpeg?q=70",
        new_price:299,
        old_price:1999,
        discount:"85%off",
        rating:4
    },
    {
        id:152,
        name:"Men Regular Fit Sol..",
        full_name:"Men Regular Fit Solid Spread Collar Formal Shirt",
        brand_name:"PETER ENGLAND ",
        category:"men-formals",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/u/h/0/-original-imagg7rhzn4fnurt.jpeg?q=70",
        new_price:1039,
        old_price:1599,
        discount:"35%off",
        rating:4.2
    },
 
   

    

    
    

]
export default shirts_data;