let all_products = [
    {
        id:1,
        name:"BLIVE Men Striped..",
        full_name:"Men Striped Round Neck Cotton Blend Multicolor T-Shirt",
        brand_name:"BLIVE",
        description:"The BLIVE Men's Round Neck T-shirt offers a blend of style, comfort, and versatility. Crafted from high-quality cotton fabric, this t-shirt ensures all-day comfort and breathability. Whether you're lounging at home or heading out for casual outings, this t-shirt is an ideal choice. Its simple yet stylish design makes it easy to pair with jeans, shorts, or casual trousers for various occasions.",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/s/z/l-bmrgyrn-dp-z12-blive-original-imahyvz9dknwfvuf.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/l186t8w0/t-shirt/m/h/n/s-bmrgyrn-z12-blive-original-imagcu32bffhwewr.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/g/5/d/l-bmrgyrn-z12-blive-original-imagx4ehf8xh3cqg.jpeg?q=70&crop=false",
        new_price:299,
        old_price:1999,
        discount:"85% off",
        rating:3.8
    },
    {
        id:2,
        name:"BEWAKOOF Men Full S..",
        full_name:"Oversized Men Graphic Print Round Neck Pure Cotton Brown T-Shirt",
        brand_name:"BEWAKOOF",
        description:"Strike a balance between being young, wild and free with this Beast Within 2.0 Men's Oversized Full Sleeve T-shirt. Pair this brown t-shirt with denim, a varsity jacket and sneakers for a dapper appeal",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/l/4/n/s-581508-bewakoof-original-imah2e4q8gkhcet5.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/o/r/1/s-581508-bewakoof-original-imah2e4q7wzpcasw.jpeg?q=70",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/k/r/3/s-581508-bewakoof-original-imah2e4qpfhr8y2b.jpeg?q=70&crop=false",
        new_price:494,
        old_price:1499,
        discount:"67% off",
        rating:3.8
    },
    {
        id:3,
        name:"Dennis Lingo Men Fit..",
        full_name:"Men Slim Fit Solid Spread Collar Casual Shirt",
        brand_name:"Dennis Lingo",
        category:"men",
        description:"Enhance your look by wearing this trendy shirt. Team it with a pair of Sharp Looking Chinos and Tassel Loafers for a Dapper Loo",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/b/w/o/s-c301-white-dennis-lingo-original-imafw2ggrk5epcfu-bb.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/u/y/xl-c301-white-dennis-lingo-original-imaff64htkhvmzfx.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kdj4xow0-0/shirt/n/j/f/xxl-c301-white-dennis-lingo-original-imaff64hm49trnkk.jpeg?q=70&crop=false",
        new_price:499,
        old_price:1899,
        discount:"80% off",
        rating:4.5
    },
    {
        id:4,
        name:"UNITED DENIM Men Re..",
        full_name:"Men Relaxed Fit Mid Rise Blue Jeans",
        brand_name:"UNITED DENIM",
        category:"men",
        description:"UNITED DENIM Elevate your style with Classic Straight-Leg Jeans. These Jeans offer a modern and flattering silhouette, suitable for various occasions. Crafted for comfort and style, their sleek black hue adds a touch of sophistication to your look. Upgrade your wardrobe with these versatile pants from United Denim.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/f/9/q/32-united192-united-denim-original-imah29yycafyfb4y.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/3/v/c/32-united192-united-denim-original-imah29yysqvftkxp.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/z/j/q/32-united192-united-denim-original-imah29yyhshzpxkg.jpeg?q=70&crop=false",
        new_price:479,
        old_price:2999,
        discount:"84% off",
        rating:3.9
    },
    {
        id:5,
        name:"WROGN Men Solid D..",
        full_name:"Men Solid Denim Jacket",
        brand_name:"WROGN",
        category:"men",
        description:"Olive green solid denim jacket with distressed detail, has a spread collar, 4 pockets, has a button closure, long sleeves, straight hemline.",
        image:"https://rukminim2.flixcart.com/image/612/612/kvtuxe80/jacket/g/j/g/xxl-no-14296102-wrogn-original-imag8nyybzwqe7kv.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/kvtuxe80/jacket/x/d/o/xxl-no-14296102-wrogn-original-imag8nyynvvjz6hz.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/kvtuxe80/jacket/x/8/2/xxl-no-14296102-wrogn-original-imag8nyyhtah7aez.jpeg?q=70&crop=false",
        new_price:2204,
        old_price:3799,
        discount:"36% off",
        rating:3.7
    },
    {
        id:6,
        name:"Sanvi Fashion Women P..",
        full_name:"Women Printed Viscose Rayon Straight Kurta(Blue)",
        brand_name:"Sanvi Fashion",
        category:"women",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/z/o/e/s-trishul-01-sanvi-fashion-original-imahfu37gzxrsag4.jpeg?q=70",
        new_price:240,
        old_price:1399,
        discount:"82% off",
        rating:3.9
    },
    {
        id:7,
        name:"Selvia Women Printed..",
        full_name:"Women Printed Viscose Rayon Straight Kurta(Blue)",
        brand_name:"Sanvi Fashion",
        category:"women",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/q/u/7/l-658tk11404-selvia-original-imahfs6grhfvakgt.jpeg?q=70",
        new_price:919,
        old_price:3063,
        discount:"69% off",
        rating:3.9
    },
    {
        id:8,
        name:"BLACK SCISSOR Women",
        full_name:"Women Printed Viscose Rayon Straight Kurta(Blue)",
        brand_name:"Sanvi Fashion",
        category:"women",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/d/i/e/m-bs-3114-black-scissor-original-imagxffqhphptzhy.jpeg?q=70",
        new_price:909,
        old_price:6363,
        discount:"85% off"
    },
    {
        id:9,
        name:"KASHIAN Women..",
        full_name:"Women Printed Viscose Rayon Straight Kurta(Blue)",
        brand_name:"Sanvi Fashion",
        category:"women",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/k/g/32-j-1320-blue-kashian-original-imagz9cwk22hhgxv.jpeg?q=70",
        new_price:455,
        old_price:1499,
        discount:"69% off"
    },
    {
        id:10,
        name:"Leotude Women Typogr..",
        full_name:"Women Printed Viscose Rayon Straight Kurta(Blue)",
        brand_name:"Sanvi Fashion",
        category:"women",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/d/w/e/3xl-grl-fs49-purpl-dragonn-leotude-original-imaghgpurfugegzb.jpeg?q=70",
        new_price:299,
        old_price:1099,
        discount:"72% off",
        rating:4.5
    },
    {
        id:11,
        name:"Men Regular Fit..",
        full_name:"Men Regular Fit Self Design Spread Collar Casual Shirt",
        brand_name:"CAMPUS SUTRA",
        category:"men",
        description:"Wear this stylish shirt from the house of Campus Sutra. The shirt is comfortable to wear as the fabrics are light on the skin. Using stellar quality solvents, the shirt is made for your daily schedule. Constructed to fit your style spot on and a wide range of sizes to match your persona. Made to not leech out its colours and not lose its shape either. Fetch a casual and cool look for yourself by teaming it with a pair of trousers and sneakers.",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/h/k/q/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrswwhtbc4d.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/b/7/t/xl-sscs24-csmssrt6019-campus-sutra-original-imagyzrskenp3fdm.jpeg?q=70&crop=false",
        new_price:854,
        old_price:1899,
        discount:"55% off",
        rating:4
    },
    {
        id:12,
        name:"Men Printed Round N..",
        full_name:"Men Printed Round Neck Pure Cotton Black T-Shirt",
        brand_name:"Mavinclub",
        category:"men",
        description:"Discover Crazybee's latest collection of oversized t-shirts for men. Shop high-quality, trendy baggy t-shirts that are perfect for everyday wear. Our comfortable oversized t-shirts for men feature modern down-shoulder designs, ensuring you stay stylish and at ease. Whether you're looking for a casual look or something more contemporary, our collection has it all. Find your perfect fit today with Crazybee's premium oversized t-shirts!",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/h/g/h/l-neverlookback-10-mavinclub-original-imah22sjktyjhkrj.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/l/f/r/l-neverlookback-10-mavinclub-original-imah22sjq9pmhazs.jpeg?q=70&crop=false",
        new_price:275,
        old_price:999,
        discount:"72% off",
        rating:3.9
    },
    {
        id:13,
        name:"Men Slim Mid Rise..",
        full_name:"Men Slim Mid Rise Blue Jeans",
        brand_name:"KILLER",
        category:"men",
        description:"Killer Mens Blue Slim Fit Stretchable Knitted Jeans",
        image:" https://rukminim2.flixcart.com/image/612/612/xif0q/jean/h/o/r/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhkajy6fdh.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/v/k/z/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhxbjqvd4d.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/jean/t/g/x/32-kjo-90427-slm-slmft-lghind-killer-original-imagzzhhgq8zavzf.jpeg?q=70&crop=false",
        new_price:1539,
        old_price:3899,
        discount:"60% off",
        rating:3.8
    },
    {
        id:14,
        name:"Synthetic Leather Lightw..",
        full_name:"Synthetic Leather Sneakers For Men (White)",
        brand_name:"aadi",
        category:"men",
        description:"Synthetic Leather |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor|Daily Use Sneakers For Men  (White)",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/j/v/9/6-tm-12-6-trm-white-original-imagjqyzntcvcmhz.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/1/i/p/7-iv-white-7-cooperwings-white-original-imagrpzpvbrhvetq.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/d/o/5/7-iv-white-7-cooperwings-white-original-imagrpzpjhryvgyv.jpeg?q=70&crop=false",
        new_price:285,
        old_price:1999,
        discount:"85% off",
        rating:3.6
    },
    {
        id:15,
        name:"Men Solid Single..",
        full_name:"Men Solid Single Breasted Festive & Wedding Blazer (Black)",
        brand_name:"FUBAR",
        category:"men",
        image:"https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/x/3/6/l-kcbz-blazer-bk-fubar-original-imahfh5qtt62vaac.jpeg?q=70",
        image_1:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/i/u/3/l-kcbz-blazer-bk-fubar-original-imahfh5qhyfczxyg.jpeg?q=70&crop=false",
        image_2:"https://rukminim2.flixcart.com/image/832/832/xif0q/blazer/i/u/3/l-kcbz-blazer-bk-fubar-original-imahfh5qhyfczxyg.jpeg?q=70&crop=false",
        new_price:1499,
        old_price:4999,
        discount:"70% off",
        rating:3.6
    },
    

]
export default all_products;